### ISSUE TITLE
Use users npm version rather than hardcoded version (npm@6)

### ISSUE THREAD

**Issue by ItamarGronich** [fiverr/published#30]
Currently, this package uses npm@6 hardcoded through the programmatic API (`const npm = require('npm')`)
This has two problems:
1. The programmatic API was removed in npm@8
2. this doesn't use the end-user's npm version.

This can cause many bugs.
One of them I've discovered today is that npm@6 publish command, will only look for `.gitignore` or `.npmrc` file in the local folder of where the current `package.json` file is.
But npm@8 also looks at parent `.gitignore` and `.npmignore` files .

Which means, that if we migrate to wrap npm@8, this means that all end users will have to somehow deal with the fact that it will now not publish anything ignored by git.
Most commonly the `dist/` folder.

Suggested solution in end packages is to use the `files: []` key in package.json.

**Comment by odeadglaz** [comment]
Another option would be to ensure each workspace that is publishing packages will include a `.npmignore` file, which than specific packages that override it could use the `file:[..]` entry which will be prioritized.

This will kinda avoid spamming this across our packages and resolved it at the workspace level

**Comment by raphaelboukara** [comment]
We stopped to use this package
